import { MigrationInterface, QueryRunner } from "typeorm";

export class PruebaCotizante1692326089643 implements MigrationInterface {
    name = 'PruebaCotizante1692326089643'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_image" DROP CONSTRAINT "FK_40ca0cd115ef1ff35351bed8da2"`);
        await queryRunner.query(`ALTER TABLE "product_image" RENAME COLUMN "productId" TO "product_id"`);
        await queryRunner.query(`CREATE TABLE "PA_TPIDENT" ("TPIDID" number NOT NULL, "TPIDNOMB" varchar2(255) NOT NULL, "TPIDABRV" varchar2(255) NOT NULL, "TPIDESTADO" varchar2(1) DEFAULT 'A' NOT NULL, "TPIDUSCR" varchar2(10) NOT NULL, "TPIDFECR" date NOT NULL, "TPIDUSACT" varchar2(10), "TPIDFEAC" date NOT NULL, "TPIDFAEL" varchar2(2), "TPIDFAELTOC" varchar2(20), CONSTRAINT "PK_8535d7d7d2d03104050917f460a" PRIMARY KEY ("TPIDID"))`);
        await queryRunner.query(`CREATE TABLE "PA_COTIZANTE" ("COTIID" number NOT NULL, "COTITPIDENT" number NOT NULL, "COTIIDENT" varchar2(200) NOT NULL, "COTINOMB" varchar2(200) NOT NULL, "COTIFECR" date NOT NULL, "COTIUSCR" varchar2(10) NOT NULL, "COTIUSACT" varchar2(10), "COTIFEAC" date, "COTIESTADO" varchar2(1) DEFAULT 'A' NOT NULL, CONSTRAINT "REL_5e5ac1f22f3b99f3507540bfcb" UNIQUE ("COTITPIDENT"), CONSTRAINT "PK_dd664220d58e37fc53b3216c2ea" PRIMARY KEY ("COTIID"))`);
        await queryRunner.query(`CREATE TABLE "AF_MARCAS_AUD" ("MARCID" number GENERATED BY DEFAULT AS IDENTITY, "MARCEMPR" number NOT NULL, "MARCNOMB" varchar2(255) NOT NULL, "MARCABRV" varchar2(255) NOT NULL, "MARCESTADO" varchar2(1) NOT NULL, "MARCUSCR" varchar2(10) NOT NULL, "MARCFECR" timestamp NOT NULL, "MARCUSACT" varchar2(10), "MARCFEAC" date, "AUDIT_ACTION" char(1), "AUDIT_BY" varchar2(50), CONSTRAINT "PK_277024923839c2076f9e62c008d" PRIMARY KEY ("MARCID"))`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "description" varchar2(255)`);
        await queryRunner.query(`ALTER TABLE "PA_COTIZANTE" ADD CONSTRAINT "FK_5e5ac1f22f3b99f3507540bfcbe" FOREIGN KEY ("COTITPIDENT") REFERENCES "PA_TPIDENT" ("TPIDID")`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_image" DROP CONSTRAINT "FK_dbc7d9aa7ed42c9141b968a9ed3"`);
        await queryRunner.query(`ALTER TABLE "PA_COTIZANTE" DROP CONSTRAINT "FK_5e5ac1f22f3b99f3507540bfcbe"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "description" varchar2(800)`);
        await queryRunner.query(`DROP TABLE "AF_MARCAS_AUD"`);
        await queryRunner.query(`DROP TABLE "PA_COTIZANTE"`);
        await queryRunner.query(`DROP TABLE "PA_TPIDENT"`);
        await queryRunner.query(`ALTER TABLE "product_image" RENAME COLUMN "product_id" TO "productId"`);
        await queryRunner.query(`ALTER TABLE "product_image" ADD CONSTRAINT "FK_40ca0cd115ef1ff35351bed8da2" FOREIGN KEY ("productId") REFERENCES "product" ("id") ON DELETE CASCADE`);
    }

}
